### ISSUE TITLE
Command protection si wrong on so many levels !

### ISSUE THREAD

**Issue by cark** [CaptainCallback/TwitchBotanist#8]
- your command protection doesn't work at all, you were able to send protected commands although you're not a mod=1
- you're protecting the wrong thing, right now you only want to protect newcommand and removecommand, while you want anyone to be able to use the dynamic commands
- after perusing the documentation, I found that you want to check the badges entry in the tag hashmap to know the mod status

**Comment by ghost** [comment]
OMG, now I see what you mean with the protection xD, this is really outright stupid! Seems like I was too tired yesterday!
I am gonna fix this now and also look into this mod stuff with the badges entry.
